add_newline = true

format = """
[╭─](bold green)$time $username$sudo$memory_usage $localip$hostname $directory$fill$cmd_duration $battery
[╰─](bold green)$status$character
"""

[fill]
symbol = " "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"

[status]
disabled = false
style = "bold red"
symbol = "X "
success_symbol = ""
format = "[$symbol$status]($style) "
map_symbol = true

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"
time_format = "%I:%M:%S %p"

[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style)"

[sudo]
disabled = true
style = "bold yellow"
format = "[$symbol]($style)"

[memory_usage]
disabled = false
threshold = 0
style = "bold dimmed green"
symbol = " "
format = "[$symbol$ram_pct]($style)"

[localip]
disabled = false
ssh_only = false
style = "bold yellow"
format = "[@$localipv4]($style) "

[hostname]
ssh_only = false
style = "bold cyan"
format = "[$hostname]($style)"
disabled = false

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold purple"
format = " in [$path]($style)[$read_only]($read_only_style)"
read_only = " RO"
read_only_style = "red"
truncation_symbol = ".../"
home_symbol = "~"

[cmd_duration]
min_time = 500
style = "bold yellow"
format = "[$duration]($style)"

[battery]
disabled = false
format = "[$symbol$percentage]($style)"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[git_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style))"

